TampaBayCoders/Controllers/ForumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace TampaBayCoders.Controllers
{
	[Authorize]
    public class ForumsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TampaBayCoders/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using TampaBayCoders.Configuration;
using TampaBayCoders.Models;
using TampaBayCoders.Services;

namespace TampaBayCoders.Controllers
{
	[Route("[controller]")]
	public class ProfileController : ControllerBase
	{
		public ProfileController(IOptions<CosmosDbSettings> cosmosDbSettings) : base(cosmosDbSettings) { }

		// GET: /Profile
		[Authorize, Route("")]
		public async Task<IActionResult> Index()
		{
			var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
			var myProfile = await ProfileService.Connect(SharedDataConnection).FindByUserId(userId);
			if (myProfile == null)
				return RedirectToAction("Create");
			return RedirectToAction("ViewProfile", new { id = myProfile.Id });
			return View("ViewProfile", myProfile);
		}

		[Route("{id}")]
		public async Task<IActionResult> ViewProfile(string id)
		{
			var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
			var myProfile = await ProfileService.Connect(SharedDataConnection).ReadAsync(id);
			if (myProfile == null)
				return RedirectToAction("Create");
			return View(myProfile);
		}

		[Authorize, HttpGet, Route("create")]
		public IActionResult Create()
		{
			var myProfile = ProfileService.Connect(SharedDataConnection).StubForUser(User);
			return View("EditProfile", myProfile);
		}

		[Authorize, HttpPost, Route("create"), ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(Profile profile)
		{
			if (!ModelState.IsValid)
				return View("EditProfile", profile);
			var createdProfile = await ProfileService.Connect(SharedDataConnection).Create(profile);
			return RedirectToAction("ViewProfile", new { id = createdProfile.Id });
		}
	}
}

TampaBayCoders/Controllers/ToolsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Documents;
using Microsoft.Azure.Documents.Client;
using Microsoft.Extensions.Options;
using TampaBayCoders.Configuration;
using TampaBayCoders.Data;
using TampaBayCoders.Models;
using TampaBayCoders.Services.CompensationCalculator;

namespace TampaBayCoders.Controllers
{
	[Route("[controller]")]
	public class ToolsController : Controller
	{
		private CosmosDbSettings _dbSettings;

		public ToolsController(IOptions<CosmosDbSettings> cosmosDbSettings) : base() { _dbSettings = cosmosDbSettings.Value; }

		[HttpGet, Route("compensation-calculator")]
		public IActionResult Compensation()
		{
			return View(new CompensationCalculatorViewModel());
		}

		[HttpPost, Route("compensation-calculator/calculate")]
		public IActionResult CompensationResult(CompensationCalculatorViewModel model)
		{
			var scenario = CompensationScenario.TypicalFullTimeJob();
			model.TaxProfile = scenario.TaxProfile;
			model.HoursOffPerYear = scenario.DaysOffPerYear * 8;
			switch (model.Calculation)
			{
				case CompensationCalculatorViewModel.CalculationType.Salary:
					if (!model.Salary.HasValue) ModelState.AddModelError("Salary", "Cannot calculate for this Salary value.");
					model.Result = scenario.CalculateSalary(model.Salary.Value);
					model.ResultComparison = scenario.SalaryRequired(model.Result.TotalCompensation);
					model.ResultCheck = Math.Abs(model.ResultComparison - model.Salary.Value) < 0.01m;
					break;
				case CompensationCalculatorViewModel.CalculationType.Wage:
					if (!model.Wage.HasValue) ModelState.AddModelError("Wage", "Cannot calculate for this Wage value.");
					model.Result = scenario.CalculateHourlyWage(model.Wage.Value);
					model.ResultComparison = scenario.WageRequired(model.Result.TotalCompensation);
					model.ResultCheck = Math.Abs(model.ResultComparison - model.Wage.Value) < 0.01m;
					break;
				case CompensationCalculatorViewModel.CalculationType.Rate:
					if (!model.Rate.HasValue) ModelState.AddModelError("Rate", "Cannot calculate for this Rate value.");
					model.Result = scenario.CalculateContractRate(model.Rate.Value);
					model.ResultComparison = scenario.ContractRateRequired(model.Result.TotalCompensation, model.Result.ActualHoursWorked);
					model.ResultCheck = Math.Abs(model.ResultComparison - model.Rate.Value) < 0.01m;
					break;
				default: throw new InvalidOperationException("Invalid Calculation Type");
			}
			return PartialView(model);
		}

		[Route("site-diagnostics")]
		public async Task<IActionResult> Diagnostics()
		{
			var results = await SiteDiagnostics.RunAsync(_dbSettings);
			return View(results);
		}

	}
}

TampaBayCoders/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@{ 
	var title = ViewData["Title"] as string;
	title = string.IsNullOrWhiteSpace(title) ? "Tampa Bay Coders" : title +  " - Tampa Bay Coders";
	var displayName = User.FindFirst(System.Security.Claims.ClaimTypes.Name)?.Value
		?? User.FindFirst(System.Security.Claims.ClaimTypes.GivenName)?.Value
		?? "Me";

}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@title</title>
	<link rel="apple-touch-icon" sizes="180x180" href="~/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="~/favicon-16x16.png">
	<link rel="manifest" href="~/manifest.json">
	<link rel="mask-icon" href="~/safari-pinned-tab.svg" color="#5bbad5">
	<meta name="theme-color" content="#ffffff">
	<environment names="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/font-awesome.css" />
		<link rel="stylesheet" href="~/css/theme.css" />
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>
	<environment names="Staging,Production">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
			  asp-fallback-href="~/css/font-awesome.min.css"
			  asp-fallback-test-class="fa-stack" asp-fallback-test-property="position" asp-fallback-test-value="relative" />
		<link rel="stylesheet" href="~/css/theme.min.css" asp-append-version="true" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
	@RenderSection("Styles", required: false)
	@Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
	<nav id="topnav" class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Tampa Bay Coders</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown">
							Site
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
							<li><a asp-area="" asp-controller="Home" asp-action="Index" asp-fragment="about">About</a></li>
							<li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
						</ul>
					</li>
					<li>
						<a asp-area="" asp-controller="Forums" asp-action="Index">
							<span class="label label-primary">
								<span class="glyphicon glyphicon-flash" title="New"></span>
							</span>
							&nbsp;
							Forums
						</a>
					</li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">
							<span class="label label-primary">
								<span class="glyphicon glyphicon-flash" title="New"></span>
							</span>
							&nbsp;
							Tools
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li><a asp-controller="Tools" asp-action="Compensation">Compensation Calculator</a></li>
							<li><a asp-controller="Tools" asp-action="Diagnostics">Site Diagnostics</a></li>
						</ul>
					</li>
					<li class="hidden"><button class="btn btn-danger navbar-btn">Contribute</button></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					@if (User.Identity.IsAuthenticated)
					{
						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#">
								@displayName
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a asp-controller="Profile" asp-action="Index">View Profile</a></li>
								<li><a asp-controller="Profile" asp-action="Edit">Edit Profile</a></li>
								<li><a asp-controller="Account" asp-action="Claims">View Claims</a></li>
								<li class="divider"></li>
								<li><a asp-controller="Account" asp-action="Logout">Logout</a></li>
							</ul>
						</li>
					}
					else
					{
						<li><a asp-controller="Account" asp-action="Login">Login</a></li>
					}
				</ul>
			</div>
		</div>
	</nav>
	@RenderBody()
	<footer class="theme inverse">
		<p>&copy; @DateTime.Now.Year - <a href="http://www.indasysllc.com" target="_blank">Indasys LLC</a></p>
	</footer>
	<environment names="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
		<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment names="Staging,Production">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"
				asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.validate"
				crossorigin="anonymous">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"
				asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.validate"
				crossorigin="anonymous">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>
	@RenderSection("Scripts", required: false)
</body>
</html>